### ISSUE TITLE
When start download,how can i know this will be success or  fail？

### ISSUE THREAD

**Issue by brucetoo** [panwrona/DownloadProgressBar#1]
downloadProgressView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                downloadProgressView.playToSuccess();
            }
        });

**Comment by panwrona** [comment]
Yeah, I know that. It was created for other project and I think that today I will add some callbacks for users to interact with the view.

**Comment by brucetoo** [comment]
That will be nice  ,Thank u. By the way,add some annotation in ur code will be perfect

**Comment by panwrona** [comment]
Great, thanks for suggestions, I apprecieate it ;) When I update the code, I will close this issue, so you know this is fixed

**Comment by brucetoo** [comment]
Yup,thank u again.

**Comment by panwrona** [comment]
Hello again, I've added method ```setProgress(value)``` for this issue. But to use this method you have to run animation with method ```playManualProgressAnimation()``` . It is originally set to result with Success State, but you can change the result with ```setErrorResultState()``` and ```setSuccessResultState``` . Also you can run the animation and immediately end progress with error state by using ```abortDownload()``` method. If something's not clear, just leave a reply here or close it.

**Comment by panwrona** [comment]
Hello again, I've added method `setProgress(value)` for this issue. But to use this method you have to run animation with method `playManualProgressAnimation()` . It is originally set to result with Success State, but you can change the result with `setErrorResultState()` and `setSuccessResultState` . Also you can run the animation and immediately end progress with error state by using `abortDownload()` method. If something's not clear just re-open the issue
