### ISSUE TITLE
How can i set MAX Progress?

### ISSUE THREAD

**Issue by silverxd20** [panwrona/DownloadProgressBar#10]
Hi, in native class Progress Bar android there are a method that let me Set the Max"` of the progress bar (Usally is 100) but if wanna set my own value how can i set it in this library? 

Here a image:
http://image.prntscr.com/image/fa3ee39d0903457fb7fa8ed0d5f02d13.png

**Comment by panwrona** [comment]
Hey,

You can use method `downloadProgressBar.setProgress(value);` . It is in description in "update" section. The value must be between 1-100
