### ISSUE TITLE
Pause Success View .

### ISSUE THREAD

**Issue by joseph27** [panwrona/DownloadProgressBar#2]
Hello ,

 thanks for such great animation .we have an enquiry here about your libary 
we are using your animation as part of an introduction screen  but after the animation finishes the Arrow view comes again . how can we pause the view of success as Tick Sign if you can give us the instructions thats would be great .
Thanks .

**Comment by panwrona** [comment]
Hello,

Thank You for those kind words ;) First of all, everything is being drawn in onDraw() method. Each step of the animation is setting the State object (which is an enum). So if you want to pause this animation on success state, you have to change the Animation Listener of Success Animation -> especially the onAnimationEnd() callback. If You don't update the State to State.IDLE and don't call the resetValues() method, the animation should stop on success value and don't go any further. 

If something's not clear, just leave a comment ;)

Cheers, PanWrona ;)

**Comment by joseph27** [comment]
Thanks for Your reply i have achieved The Desire View by removing  
      resetValues();  &  invalidate(); onAnimationEnd 

Thanks again.

**Comment by panwrona** [comment]
Happy to hear that, cheers ;)
