### ISSUE TITLE
hey please fix this...

### ISSUE THREAD

**Issue by stickylabdev** [panwrona/DownloadProgressBar#4]
This manifest is always shown error even when u change to  1 and 1.0 it alwways always error really .

```
package="com.panwrona.downloadprog
android:versionCode="+"
android:versionName="STRING_CONSTRUCT"
```

**Comment by panwrona** [comment]
Where do you have this?

**Comment by stickylabdev** [comment]
Android manifest .that error always and akways appear even when i rebuild clear  data and anything :'(

**Comment by panwrona** [comment]
But in the library it is not. There must be problem with your project
