### ISSUE TITLE
How I can learn? 

### ISSUE THREAD

**Issue by victortu** [panwrona/DownloadProgressBar#9]
Congratulations!

How cool this design and everything! So cool! I love :)

I would like to learn how to design and create animations how are you with programming.

How I can learn? How do I search in Google or meeting?

Thanks for your time!

**Comment by panwrona** [comment]
If you type "android animation" you will have some results with tutorials. However - if you type "android animation tutorial" in Google, you will have tons of results :) 

The best way to learn is to follow some tutorials first and then code your own animation. Also if you want some inspiration, there are some webpages:

www.materialup.com
www.dribbble.com
www.behance.net

Have a nice day ;)
